{-# OPTIONS --safe --without-K #-}

module Disciplines.Graph.K12ZSpanIJ where

open import FirstDistinction
open import Disciplines.Math.Counting
open import Disciplines.Math.Integers
open import Disciplines.Math.IntegersLaws
open import Disciplines.Math.FiniteSumsZ
open import Disciplines.Math.IntegerMultiplication
open import Disciplines.Math.IntegerMultiplicationLaws
open import Disciplines.Graph.K4MatrixLaplacian
open import Disciplines.Graph.K4TripleCoupledLaplacian
open import Disciplines.Graph.K12IteratedOperatorAlgebra

{-
CHAPTER 14N: ℤ-Span Of K₁₂ Operators (I,J) As A Forced Normal Form

ONTOLOGICAL STATUS: Derived
DEPENDENCIES: Chapter 14H (K₁₂ operators), Chapter 14M (ℤ multiplication)
AGDA MODULES: Disciplines.Graph.K12ZSpanIJ
DEGREES OF FREEDOM ELIMINATED: ambiguous integer-linear representation of endomorphisms generated by I and J
-}

-- Endomorphisms on Vec12ℤ, with pointwise equality.

Op : Set
Op = Vec12ℤ → Vec12ℤ

OpEq : Op → Op → Set
OpEq f g = (v : Vec12ℤ) → Vec12Eq (f v) (g v)

zeroOp : Op
zeroOp _ = zeroVec12ℤ

I12 : Op
I12 v = v

scaleVec4ℤ : ℤ → Vec4ℤ → Vec4ℤ
scaleVec4ℤ a v i = a *ℤ v i

scaleVec12ℤ : ℤ → Vec12ℤ → Vec12ℤ
scaleVec12ℤ a v = scaleVec4ℤ a (block₀ v) , (scaleVec4ℤ a (block₁ v) , scaleVec4ℤ a (block₂ v))

linIJ : ℤ → ℤ → Op
linIJ a b v = scaleVec12ℤ a v +Vec12ℤ scaleVec12ℤ b (J12Vec12ℤ v)

block₀-linIJ : (a b : ℤ) → (v : Vec12ℤ) → (i : Fin4) →
  block₀ (linIJ a b v) i ≡ (a *ℤ block₀ v i) +ℤ (b *ℤ sum12ℤ v)
block₀-linIJ a b v i = refl

block₁-linIJ : (a b : ℤ) → (v : Vec12ℤ) → (i : Fin4) →
  block₁ (linIJ a b v) i ≡ (a *ℤ block₁ v i) +ℤ (b *ℤ sum12ℤ v)
block₁-linIJ a b v i = refl

block₂-linIJ : (a b : ℤ) → (v : Vec12ℤ) → (i : Fin4) →
  block₂ (linIJ a b v) i ≡ (a *ℤ block₂ v i) +ℤ (b *ℤ sum12ℤ v)
block₂-linIJ a b v i = refl

-- Reassociation helper: regroup six-term sums into (v-side) + (w-side).

shuffle3Pairs : (A A' B B' C C' : ℤ) →
  (A +ℤ A') +ℤ ((B +ℤ B') +ℤ (C +ℤ C')) ≡ (A +ℤ (B +ℤ C)) +ℤ (A' +ℤ (B' +ℤ C'))
shuffle3Pairs A A' B B' C C' =
  let
    X = (B +ℤ B') +ℤ (C +ℤ C')

    step₁ : (A +ℤ A') +ℤ X ≡ A +ℤ (A' +ℤ X)
    step₁ = +ℤ-assoc A A' X

    step₂ : A' +ℤ X ≡ A' +ℤ (B +ℤ (B' +ℤ (C +ℤ C')))
    step₂ = cong (λ t → A' +ℤ t) (+ℤ-assoc B B' (C +ℤ C'))

    step₃ : A' +ℤ (B +ℤ (B' +ℤ (C +ℤ C'))) ≡ B +ℤ (A' +ℤ (B' +ℤ (C +ℤ C')))
    step₃ = swapHeadℤ A' B (B' +ℤ (C +ℤ C'))

    step₄ : A' +ℤ (B' +ℤ (C +ℤ C')) ≡ C +ℤ (A' +ℤ (B' +ℤ C'))
    step₄ =
      trans
        (cong (λ t → A' +ℤ t) (swapHeadℤ B' C C'))
        (swapHeadℤ A' C (B' +ℤ C'))

    step₅ : B +ℤ (A' +ℤ (B' +ℤ (C +ℤ C'))) ≡ B +ℤ (C +ℤ (A' +ℤ (B' +ℤ C')))
    step₅ = cong (λ t → B +ℤ t) step₄

    step₆ : A +ℤ (B +ℤ (C +ℤ (A' +ℤ (B' +ℤ C')))) ≡ (A +ℤ (B +ℤ C)) +ℤ (A' +ℤ (B' +ℤ C'))
    step₆ =
      trans
        (cong (λ t → A +ℤ t) (sym (+ℤ-assoc B C (A' +ℤ (B' +ℤ C')))))
        (sym (+ℤ-assoc A (B +ℤ C) (A' +ℤ (B' +ℤ C'))))
  in
  trans
    step₁
    (trans
      (cong (λ t → A +ℤ t) (trans step₂ (trans step₃ step₅)))
      step₆)

-- Finite-sum scaling forced by right distributivity.

sumFin4-scaleVec4ℤ : (a : ℤ) → (v : Vec4ℤ) →
  sumFin4ℤ (scaleVec4ℤ a v) ≡ a *ℤ sumFin4ℤ v
sumFin4-scaleVec4ℤ a v =
  let
    v0 = v g0
    v1 = v g1
    v2 = v g2
    v3 = v g3

    expand : a *ℤ (v0 +ℤ (v1 +ℤ (v2 +ℤ v3))) ≡ (a *ℤ v0) +ℤ ((a *ℤ v1) +ℤ ((a *ℤ v2) +ℤ (a *ℤ v3)))
    expand =
      trans
        (*ℤ-distrib-right-+ℤ a v0 (v1 +ℤ (v2 +ℤ v3)))
        (cong (λ t → (a *ℤ v0) +ℤ t)
          (trans
            (*ℤ-distrib-right-+ℤ a v1 (v2 +ℤ v3))
            (cong (λ t → (a *ℤ v1) +ℤ t)
              (*ℤ-distrib-right-+ℤ a v2 v3))))
  in
  sym expand

sum12-+Vec12ℤ : (v w : Vec12ℤ) → sum12ℤ (v +Vec12ℤ w) ≡ sum12ℤ v +ℤ sum12ℤ w
sum12-+Vec12ℤ v w =
  let
    A  = sumFin4ℤ (block₀ v)
    B  = sumFin4ℤ (block₁ v)
    C  = sumFin4ℤ (block₂ v)
    A' = sumFin4ℤ (block₀ w)
    B' = sumFin4ℤ (block₁ w)
    C' = sumFin4ℤ (block₂ w)
  in
  trans
    refl
    (trans
      (cong
        (λ t → t +ℤ (sumFin4ℤ (block₁ (v +Vec12ℤ w)) +ℤ sumFin4ℤ (block₂ (v +Vec12ℤ w))))
        (sumFin4-+Vec4ℤ (block₀ v) (block₀ w)))
      (trans
        (cong
          (λ t → (A +ℤ A') +ℤ (t +ℤ sumFin4ℤ (block₂ (v +Vec12ℤ w))) )
          (sumFin4-+Vec4ℤ (block₁ v) (block₁ w)))
        (trans
          (cong
            (λ t → (A +ℤ A') +ℤ ((B +ℤ B') +ℤ t))
            (sumFin4-+Vec4ℤ (block₂ v) (block₂ w)))
          (shuffle3Pairs A A' B B' C C'))))

sum12-scaleVec12ℤ : (a : ℤ) → (v : Vec12ℤ) → sum12ℤ (scaleVec12ℤ a v) ≡ a *ℤ sum12ℤ v
sum12-scaleVec12ℤ a v =
  let
    s0 = sumFin4ℤ (block₀ v)
    s1 = sumFin4ℤ (block₁ v)
    s2 = sumFin4ℤ (block₂ v)
  in
  let
    stepBlock : sum12ℤ (scaleVec12ℤ a v) ≡ (a *ℤ s0) +ℤ ((a *ℤ s1) +ℤ (a *ℤ s2))
    stepBlock =
      trans
        refl
        (trans
          (cong
            (λ t → t +ℤ (sumFin4ℤ (scaleVec4ℤ a (block₁ v)) +ℤ sumFin4ℤ (scaleVec4ℤ a (block₂ v))))
            (sumFin4-scaleVec4ℤ a (block₀ v)))
          (trans
            (cong
              (λ t → (a *ℤ s0) +ℤ (t +ℤ sumFin4ℤ (scaleVec4ℤ a (block₂ v))) )
              (sumFin4-scaleVec4ℤ a (block₁ v)))
            (cong
              (λ t → (a *ℤ s0) +ℤ ((a *ℤ s1) +ℤ t))
              (sumFin4-scaleVec4ℤ a (block₂ v)))))

    fold : a *ℤ (s0 +ℤ (s1 +ℤ s2)) ≡ (a *ℤ s0) +ℤ ((a *ℤ s1) +ℤ (a *ℤ s2))
    fold =
      trans
        (*ℤ-distrib-right-+ℤ a s0 (s1 +ℤ s2))
        (cong (λ t → (a *ℤ s0) +ℤ t) (*ℤ-distrib-right-+ℤ a s1 s2))
  in
  trans stepBlock (sym fold)

-- Interaction between multiplication and the forced 12-times operator.

*ℤ-fourTimes-right : (x y : ℤ) → x *ℤ fourTimesℤ y ≡ fourTimesℤ (x *ℤ y)
*ℤ-fourTimes-right x y =
  trans
    (*ℤ-distrib-right-+ℤ x y (y +ℤ (y +ℤ y)))
    (cong (λ t → (x *ℤ y) +ℤ t)
      (trans
        (*ℤ-distrib-right-+ℤ x y (y +ℤ y))
        (cong (λ t → (x *ℤ y) +ℤ t)
          (*ℤ-distrib-right-+ℤ x y y))))

*ℤ-fourTimes-left : (x y : ℤ) → fourTimesℤ x *ℤ y ≡ fourTimesℤ (x *ℤ y)
*ℤ-fourTimes-left x y =
  trans
    (*ℤ-distrib-left-+ℤ x (x +ℤ (x +ℤ x)) y)
    (cong (λ t → (x *ℤ y) +ℤ t)
      (trans
        (*ℤ-distrib-left-+ℤ x (x +ℤ x) y)
        (cong (λ t → (x *ℤ y) +ℤ t)
          (*ℤ-distrib-left-+ℤ x x y))))

*ℤ-eightTimes-right : (x y : ℤ) → x *ℤ eightTimesℤ y ≡ eightTimesℤ (x *ℤ y)
*ℤ-eightTimes-right x y =
  trans
    (*ℤ-distrib-right-+ℤ x (fourTimesℤ y) (fourTimesℤ y))
    (cong (λ t → t +ℤ t) (*ℤ-fourTimes-right x y))

*ℤ-eightTimes-left : (x y : ℤ) → eightTimesℤ x *ℤ y ≡ eightTimesℤ (x *ℤ y)
*ℤ-eightTimes-left x y =
  trans
    (*ℤ-distrib-left-+ℤ (fourTimesℤ x) (fourTimesℤ x) y)
    (cong (λ t → t +ℤ t) (*ℤ-fourTimes-left x y))

*ℤ-twelveTimes-right : (x y : ℤ) → x *ℤ twelveTimesℤ y ≡ twelveTimesℤ (x *ℤ y)
*ℤ-twelveTimes-right x y =
  trans
    (*ℤ-distrib-right-+ℤ x (fourTimesℤ y) (eightTimesℤ y))
    (trans
      (cong (λ t → t +ℤ x *ℤ eightTimesℤ y) (*ℤ-fourTimes-right x y))
      (cong (λ t → fourTimesℤ (x *ℤ y) +ℤ t) (*ℤ-eightTimes-right x y)))

*ℤ-twelveTimes-left : (x y : ℤ) → twelveTimesℤ x *ℤ y ≡ twelveTimesℤ (x *ℤ y)
*ℤ-twelveTimes-left x y =
  trans
    (*ℤ-distrib-left-+ℤ (fourTimesℤ x) (eightTimesℤ x) y)
    (trans
      (cong (λ t → t +ℤ eightTimesℤ x *ℤ y) (*ℤ-fourTimes-left x y))
      (cong (λ t → fourTimesℤ (x *ℤ y) +ℤ t) (*ℤ-eightTimes-left x y)))

mul-twelveShift : (x y : ℤ) → x *ℤ twelveTimesℤ y ≡ twelveTimesℤ x *ℤ y
mul-twelveShift x y = trans (*ℤ-twelveTimes-right x y) (sym (*ℤ-twelveTimes-left x y))

-- Sum of an (I,J)-combination.

sum12-linIJ : (a b : ℤ) → (v : Vec12ℤ) →
  sum12ℤ (linIJ a b v) ≡ (a *ℤ sum12ℤ v) +ℤ (b *ℤ twelveTimesℤ (sum12ℤ v))
sum12-linIJ a b v =
  let
    s = sum12ℤ v
    step₁ : sum12ℤ (linIJ a b v)
              ≡ sum12ℤ (scaleVec12ℤ a v) +ℤ sum12ℤ (scaleVec12ℤ b (J12Vec12ℤ v))
    step₁ = sum12-+Vec12ℤ (scaleVec12ℤ a v) (scaleVec12ℤ b (J12Vec12ℤ v))

    step₂ : sum12ℤ (scaleVec12ℤ a v) ≡ a *ℤ s
    step₂ = sum12-scaleVec12ℤ a v

    step₃ : sum12ℤ (scaleVec12ℤ b (J12Vec12ℤ v)) ≡ b *ℤ sum12ℤ (J12Vec12ℤ v)
    step₃ = sum12-scaleVec12ℤ b (J12Vec12ℤ v)

    step₄ : b *ℤ sum12ℤ (J12Vec12ℤ v) ≡ b *ℤ twelveTimesℤ s
    step₄ = cong (λ t → b *ℤ t) (sum12-J12 v)
  in
  trans
    step₁
    (trans
      (cong (λ t → t +ℤ sum12ℤ (scaleVec12ℤ b (J12Vec12ℤ v))) step₂)
      (cong (λ t → (a *ℤ s) +ℤ t) (trans step₃ step₄)))


-- A single-coordinate delta vector on Fin4.

delta4 : Fin4 → ℤ → Vec4ℤ
delta4 g0 x g0 = x
delta4 g0 x g1 = 0ℤ
delta4 g0 x g2 = 0ℤ
delta4 g0 x g3 = 0ℤ

delta4 g1 x g0 = 0ℤ
delta4 g1 x g1 = x
delta4 g1 x g2 = 0ℤ
delta4 g1 x g3 = 0ℤ

delta4 g2 x g0 = 0ℤ
delta4 g2 x g1 = 0ℤ
delta4 g2 x g2 = x
delta4 g2 x g3 = 0ℤ

delta4 g3 x g0 = 0ℤ
delta4 g3 x g1 = 0ℤ
delta4 g3 x g2 = 0ℤ
delta4 g3 x g3 = x

sumFin4-delta4 : (i : Fin4) → (x : ℤ) → sumFin4ℤ (delta4 i x) ≡ x
sumFin4-delta4 g0 x =
  trans
    (cong (λ t → x +ℤ t)
      (trans
        (+ℤ-zero-left (0ℤ +ℤ 0ℤ))
        (+ℤ-zero-left 0ℤ)))
    (+ℤ-zero-right x)
sumFin4-delta4 g1 x =
  trans
    (+ℤ-zero-left (x +ℤ (0ℤ +ℤ 0ℤ)))
    (trans
      (cong (λ t → x +ℤ t) (+ℤ-zero-left 0ℤ))
      (+ℤ-zero-right x))
sumFin4-delta4 g2 x =
  trans
    (+ℤ-zero-left (0ℤ +ℤ (x +ℤ 0ℤ)))
    (trans
      (+ℤ-zero-left (x +ℤ 0ℤ))
      (+ℤ-zero-right x))
sumFin4-delta4 g3 x =
  trans
    (+ℤ-zero-left (0ℤ +ℤ (0ℤ +ℤ x)))
    (trans
      (+ℤ-zero-left (0ℤ +ℤ x))
      (+ℤ-zero-left x))

-- Delta vector on Vec12ℤ supported at (block₀, g0).

delta12 : ℤ → Vec12ℤ
delta12 x = delta4 g0 x , (delta4 g0 0ℤ , delta4 g0 0ℤ)

sum12-delta12 : (x : ℤ) → sum12ℤ (delta12 x) ≡ x
sum12-delta12 x =
  trans
    (cong (λ t → t +ℤ (sumFin4ℤ (delta4 g0 0ℤ) +ℤ sumFin4ℤ (delta4 g0 0ℤ)))
          (sumFin4-delta4 g0 x))
    (trans
      (cong (λ t → x +ℤ t)
            (cong (λ t → t +ℤ sumFin4ℤ (delta4 g0 0ℤ)) (sumFin4-delta4 g0 0ℤ)))
      (trans
        (cong (λ t → x +ℤ (0ℤ +ℤ t)) (sumFin4-delta4 g0 0ℤ))
        (trans
          (cong (λ t → x +ℤ t) (+ℤ-zero-left 0ℤ))
          (+ℤ-zero-right x))))

J12-delta12-const : (x : ℤ) → Vec12Eq (J12Vec12ℤ (delta12 x)) (constVec12ℤ x)
J12-delta12-const x =
  let p = sum12-delta12 x in
  (λ _ → p) , ((λ _ → p) , (λ _ → p))

{-
## Forced Independence

### Law 14N.0: `(a·I + b·J) = 0` Forces `a = 0` And `b = 0`
**Necessity Proof:** Evaluate the operator on the delta vector supported at one coordinate.
At a different coordinate, the `I`-term vanishes while `J` remains constant with value `b·x`.
Multiplication-right-identity (Law 14M) collapses `b·1 = b`.
**Formal Reference:** K12ZSpanIJ.agda.law14N-0-IJ-independent (lines 344-401)
**Consequence:** Eliminates degrees of freedom in ℤ-linear representation: coefficients in the `(I,J)` basis are forced to be unique.
-}

law14N-0-IJ-independent : (a b : ℤ) → OpEq (linIJ a b) zeroOp → (a ≡ 0ℤ) × (b ≡ 0ℤ)
law14N-0-IJ-independent a b hyp = a0 , b0
  where
    v : Vec12ℤ
    v = delta12 oneℤ

    pSum : sum12ℤ v ≡ oneℤ
    pSum = sum12-delta12 oneℤ

    -- q = (block₀, g1): v(g1)=0, hence the `I`-term vanishes.
    eqQraw : block₀ (linIJ a b v) g1 ≡ block₀ (zeroOp v) g1
    eqQraw = fst (hyp v) g1

    eqQ₀ : (a *ℤ 0ℤ) +ℤ (b *ℤ sum12ℤ v) ≡ 0ℤ
    eqQ₀ = trans (sym (block₀-linIJ a b v g1)) eqQraw

    eqQ₁ : (a *ℤ 0ℤ) +ℤ (b *ℤ oneℤ) ≡ 0ℤ
    eqQ₁ = trans (sym (cong (λ t → (a *ℤ 0ℤ) +ℤ (b *ℤ t)) pSum)) eqQ₀

    eqQ₂ : 0ℤ +ℤ (b *ℤ oneℤ) ≡ 0ℤ
    eqQ₂ =
      trans
        (sym (cong (λ t → t +ℤ (b *ℤ oneℤ)) (*ℤ-zero-right a)))
        eqQ₁

    bAtQ : (b *ℤ oneℤ) ≡ 0ℤ
    bAtQ = trans (sym (+ℤ-zero-left (b *ℤ oneℤ))) eqQ₂

    b0 : b ≡ 0ℤ
    b0 = trans (sym (*ℤ-one-right b)) bAtQ

    -- p = (block₀, g0): v(g0)=1.
    eqPraw : block₀ (linIJ a b v) g0 ≡ block₀ (zeroOp v) g0
    eqPraw = fst (hyp v) g0

    eqP₀ : (a *ℤ oneℤ) +ℤ (b *ℤ sum12ℤ v) ≡ 0ℤ
    eqP₀ = trans (sym (block₀-linIJ a b v g0)) eqPraw

    eqP₁ : (a *ℤ oneℤ) +ℤ (b *ℤ oneℤ) ≡ 0ℤ
    eqP₁ = trans (sym (cong (λ t → (a *ℤ oneℤ) +ℤ (b *ℤ t)) pSum)) eqP₀

    eqP₂ : (a *ℤ oneℤ) +ℤ (0ℤ *ℤ oneℤ) ≡ 0ℤ
    eqP₂ =
      trans
        (sym (cong (λ t → (a *ℤ oneℤ) +ℤ (t *ℤ oneℤ)) b0))
        eqP₁

    eqP₃ : (a *ℤ oneℤ) +ℤ 0ℤ ≡ 0ℤ
    eqP₃ =
      trans
        (sym (cong (λ t → (a *ℤ oneℤ) +ℤ t) (*ℤ-zero-left oneℤ)))
        eqP₂

    aAtP : (a *ℤ oneℤ) ≡ 0ℤ
    aAtP = trans (sym (+ℤ-zero-right (a *ℤ oneℤ))) eqP₃

    a0 : a ≡ 0ℤ
    a0 = trans (sym (*ℤ-one-right a)) aAtP

-- Right-cancellation for +ℤ forced by additive inverse.

+ℤ-cancel-right : (a c b : ℤ) → a +ℤ b ≡ c +ℤ b → a ≡ c
+ℤ-cancel-right a c b eq =
  let eq' = cong (λ t → negℤ b +ℤ t) eq in
  trans
    (sym (reduce a))
    (trans eq' (reduce c))
  where
    reduce : (x : ℤ) → negℤ b +ℤ (x +ℤ b) ≡ x
    reduce x =
      trans
        (swapHeadℤ (negℤ b) x b)
        (trans
          (cong (λ t → x +ℤ t) (+ℤ-inv-left b))
          (+ℤ-zero-right x))

{-
### Law 14N.1: `(a·I + b·J) = (c·I + d·J)` Forces `a = c` And `b = d`
**Necessity Proof:** Evaluate both operators on the delta vector supported at one coordinate.
At a different coordinate, the `I`-term vanishes, forcing `b = d`.
Then at the supported coordinate, right-cancellation forces `a = c`.
**Formal Reference:** K12ZSpanIJ.agda.law14N-1-IJ-unique (lines 429-498)
**Consequence:** Eliminates all ambiguity: the `(I,J)` normal form has forced unique coefficients.
-}

law14N-1-IJ-unique : (a b c d : ℤ) → OpEq (linIJ a b) (linIJ c d) → (a ≡ c) × (b ≡ d)
law14N-1-IJ-unique a b c d hyp = aEq , bEq
  where
    v : Vec12ℤ
    v = delta12 oneℤ

    pSum : sum12ℤ v ≡ oneℤ
    pSum = sum12-delta12 oneℤ

    eqQraw : block₀ (linIJ a b v) g1 ≡ block₀ (linIJ c d v) g1
    eqQraw = fst (hyp v) g1

    eqQ₀ : (a *ℤ 0ℤ) +ℤ (b *ℤ sum12ℤ v) ≡ (c *ℤ 0ℤ) +ℤ (d *ℤ sum12ℤ v)
    eqQ₀ =
      trans (sym (block₀-linIJ a b v g1))
        (trans eqQraw (block₀-linIJ c d v g1))

    eqQ₁a : (a *ℤ 0ℤ) +ℤ (b *ℤ sum12ℤ v) ≡ 0ℤ +ℤ (b *ℤ sum12ℤ v)
    eqQ₁a = cong (λ t → t +ℤ (b *ℤ sum12ℤ v)) (*ℤ-zero-right a)

    eqQ₁c : (c *ℤ 0ℤ) +ℤ (d *ℤ sum12ℤ v) ≡ 0ℤ +ℤ (d *ℤ sum12ℤ v)
    eqQ₁c = cong (λ t → t +ℤ (d *ℤ sum12ℤ v)) (*ℤ-zero-right c)

    eqQ₁ : 0ℤ +ℤ (b *ℤ sum12ℤ v) ≡ 0ℤ +ℤ (d *ℤ sum12ℤ v)
    eqQ₁ = trans (sym eqQ₁a) (trans eqQ₀ eqQ₁c)

    eqQ₂ : 0ℤ +ℤ (b *ℤ oneℤ) ≡ 0ℤ +ℤ (d *ℤ oneℤ)
    eqQ₂ =
      trans
        (cong (λ t → 0ℤ +ℤ (b *ℤ t)) pSum)
        (trans eqQ₁ (sym (cong (λ t → 0ℤ +ℤ (d *ℤ t)) pSum)))

    bEq' : (b *ℤ oneℤ) ≡ (d *ℤ oneℤ)
    bEq' =
      trans
        (sym (+ℤ-zero-left (b *ℤ oneℤ)))
        (trans eqQ₂ (+ℤ-zero-left (d *ℤ oneℤ)))

    bEq : b ≡ d
    bEq =
      trans (sym (*ℤ-one-right b))
        (trans bEq' (*ℤ-one-right d))

    eqPraw : block₀ (linIJ a b v) g0 ≡ block₀ (linIJ c d v) g0
    eqPraw = fst (hyp v) g0

    eqP₀ : (a *ℤ oneℤ) +ℤ (b *ℤ sum12ℤ v) ≡ (c *ℤ oneℤ) +ℤ (d *ℤ sum12ℤ v)
    eqP₀ =
      trans (sym (block₀-linIJ a b v g0))
        (trans eqPraw (block₀-linIJ c d v g0))

    eqP₁ : (a *ℤ oneℤ) +ℤ (b *ℤ oneℤ) ≡ (c *ℤ oneℤ) +ℤ (d *ℤ oneℤ)
    eqP₁ =
      trans (cong (λ t → (a *ℤ oneℤ) +ℤ (b *ℤ t)) pSum)
        (trans eqP₀ (sym (cong (λ t → (c *ℤ oneℤ) +ℤ (d *ℤ t)) pSum)))

    eqP₂ : (a *ℤ oneℤ) +ℤ (b *ℤ oneℤ) ≡ (c *ℤ oneℤ) +ℤ (b *ℤ oneℤ)
    eqP₂ =
      trans
        eqP₁
        (cong (λ t → (c *ℤ oneℤ) +ℤ t)
          (cong (λ z → z *ℤ oneℤ) (sym bEq)))

    aEq' : (a *ℤ oneℤ) ≡ (c *ℤ oneℤ)
    aEq' = +ℤ-cancel-right (a *ℤ oneℤ) (c *ℤ oneℤ) (b *ℤ oneℤ) eqP₂

    aEq : a ≡ c
    aEq =
      trans (sym (*ℤ-one-right a))
        (trans aEq' (*ℤ-one-right c))

-- Packaging: the forced (I,J) normal form is the unique witness surviving elimination.

SpanIJ : Set
SpanIJ = ℤ × ℤ

interpIJ : SpanIJ → Op
interpIJ ab = linIJ (fst ab) (snd ab)

interpIJ-injective : (p q : SpanIJ) → OpEq (interpIJ p) (interpIJ q) → p ≡ q
interpIJ-injective (a , b) (c , d) eq =
  let res = law14N-1-IJ-unique a b c d eq in
  pair-ext (fst res) (snd res)
  where
    pair-ext : {a b c d : ℤ} → a ≡ c → b ≡ d → (a , b) ≡ (c , d)
    pair-ext refl refl = refl

{-
### Law 14N.2: Existence Witness In The Image Of `interpIJ` Is Forced Unique
**Necessity Proof:** Any two witnesses induce an equality `linIJ a b = linIJ c d`; Law 14N.1 forces `(a,b)=(c,d)`.
**Formal Reference:** K12ZSpanIJ.agda.law14N-2-image-witness-unique (lines 523-528)
**Consequence:** Eliminates freedom in “choosing coefficients” once membership in the span is witnessed.
-}

law14N-2-image-witness-unique :
  (f : Op) →
  (w₁ w₂ : Σ SpanIJ (λ p → OpEq f (interpIJ p))) →
  fst w₁ ≡ fst w₂
law14N-2-image-witness-unique f (p₁ , eq₁) (p₂ , eq₂) =
  interpIJ-injective p₁ p₂ (λ v → Vec12Eq-trans (Vec12Eq-sym (eq₁ v)) (eq₂ v))

{-
### Law 14N.3: Closure Of The `(I,J)`-Span Under Composition Is Forced
**Necessity Proof:** Expand `(a·I+b·J) ∘ (c·I+d·J)` pointwise. The `I`-coefficient forces to `a·c`.
The `J`-coefficient forces to `(a·d + b·c + 12·(b·d))` since `J∘J = 12·J` and `twelveTimesℤ` commutes with
left/right multiplication by distributivity.
**Formal Reference:** K12ZSpanIJ.agda.law14N-3-IJ-compose-closed
**Consequence:** Eliminates freedom in composing witnesses: the span is a forced submonoid of endomorphisms.
-}

mulSpanIJ : SpanIJ → SpanIJ → SpanIJ
mulSpanIJ (a , b) (c , d) = (a *ℤ c) , (((a *ℤ d) +ℤ (b *ℤ c)) +ℤ twelveTimesℤ (b *ℤ d))

law14N-3-IJ-compose-closed : (p q : SpanIJ) → OpEq (λ v → interpIJ p (interpIJ q v)) (interpIJ (mulSpanIJ p q))
law14N-3-IJ-compose-closed (a , b) (c , d) v = eq0 , (eq1 , eq2)
  where
    s : ℤ
    s = sum12ℤ v

    w : Vec12ℤ
    w = linIJ c d v

    sw : sum12ℤ w ≡ (c *ℤ s) +ℤ (d *ℤ twelveTimesℤ s)
    sw = sum12-linIJ c d v

    b' : ℤ
    b' = ((a *ℤ d) +ℤ (b *ℤ c)) +ℤ twelveTimesℤ (b *ℤ d)

    blkEq :
      (blk : Vec12ℤ → Vec4ℤ) →
      ((x y : ℤ) → (u : Vec12ℤ) → (i : Fin4) → blk (linIJ x y u) i ≡ (x *ℤ blk u i) +ℤ (y *ℤ sum12ℤ u)) →
      (i : Fin4) →
      blk (linIJ a b w) i ≡ blk (linIJ (a *ℤ c) b' v) i
    blkEq blk blk-lin i =
      let
        vi = blk v i

        lhsForm : blk (linIJ a b w) i ≡ (a *ℤ blk w i) +ℤ (b *ℤ sum12ℤ w)
        lhsForm = blk-lin a b w i

        blkW : blk w i ≡ (c *ℤ vi) +ℤ (d *ℤ s)
        blkW = blk-lin c d v i

        rhsForm : blk (linIJ (a *ℤ c) b' v) i ≡ ((a *ℤ c) *ℤ vi) +ℤ (b' *ℤ s)
        rhsForm = blk-lin (a *ℤ c) b' v i

        step₁ : blk (linIJ a b w) i ≡ (a *ℤ ((c *ℤ vi) +ℤ (d *ℤ s))) +ℤ (b *ℤ sum12ℤ w)
        step₁ =
          trans
            lhsForm
            (cong (λ t → (a *ℤ t) +ℤ (b *ℤ sum12ℤ w)) blkW)

        step₂ : (a *ℤ ((c *ℤ vi) +ℤ (d *ℤ s))) +ℤ (b *ℤ sum12ℤ w)
                  ≡ ((a *ℤ (c *ℤ vi)) +ℤ (a *ℤ (d *ℤ s))) +ℤ (b *ℤ sum12ℤ w)
        step₂ = cong (λ t → t +ℤ (b *ℤ sum12ℤ w)) (*ℤ-distrib-right-+ℤ a (c *ℤ vi) (d *ℤ s))

        assocAC : a *ℤ (c *ℤ vi) ≡ (a *ℤ c) *ℤ vi
        assocAC = sym (*ℤ-assoc a c vi)

        assocAD : a *ℤ (d *ℤ s) ≡ (a *ℤ d) *ℤ s
        assocAD = sym (*ℤ-assoc a d s)

        step₃ : ((a *ℤ (c *ℤ vi)) +ℤ (a *ℤ (d *ℤ s))) +ℤ (b *ℤ sum12ℤ w)
                  ≡ (((a *ℤ c) *ℤ vi) +ℤ ((a *ℤ d) *ℤ s)) +ℤ (b *ℤ sum12ℤ w)
        step₃ =
          cong (λ t → t +ℤ (b *ℤ sum12ℤ w))
            (trans
              (cong (λ t → t +ℤ (a *ℤ (d *ℤ s))) assocAC)
              (cong (λ t → ((a *ℤ c) *ℤ vi) +ℤ t) assocAD))

        step₄ : (((a *ℤ c) *ℤ vi) +ℤ ((a *ℤ d) *ℤ s)) +ℤ (b *ℤ sum12ℤ w)
                  ≡ (((a *ℤ c) *ℤ vi) +ℤ ((a *ℤ d) *ℤ s)) +ℤ (b *ℤ ((c *ℤ s) +ℤ (d *ℤ twelveTimesℤ s)))
        step₄ = cong (λ t → (((a *ℤ c) *ℤ vi) +ℤ ((a *ℤ d) *ℤ s)) +ℤ (b *ℤ t)) sw

        step₅ : b *ℤ ((c *ℤ s) +ℤ (d *ℤ twelveTimesℤ s))
                  ≡ (b *ℤ (c *ℤ s)) +ℤ (b *ℤ (d *ℤ twelveTimesℤ s))
        step₅ = *ℤ-distrib-right-+ℤ b (c *ℤ s) (d *ℤ twelveTimesℤ s)

        step₆ : b *ℤ (c *ℤ s) ≡ (b *ℤ c) *ℤ s
        step₆ = sym (*ℤ-assoc b c s)

        step₇ : b *ℤ (d *ℤ twelveTimesℤ s) ≡ (twelveTimesℤ (b *ℤ d)) *ℤ s
        step₇ =
          trans
            (sym (*ℤ-assoc b d (twelveTimesℤ s)))
            (mul-twelveShift (b *ℤ d) s)

        step₈ : b *ℤ ((c *ℤ s) +ℤ (d *ℤ twelveTimesℤ s))
                  ≡ ((b *ℤ c) *ℤ s) +ℤ ((twelveTimesℤ (b *ℤ d)) *ℤ s)
        step₈ =
          trans
            step₅
            (trans
              (cong (λ t → t +ℤ (b *ℤ (d *ℤ twelveTimesℤ s))) step₆)
              (cong (λ t → ((b *ℤ c) *ℤ s) +ℤ t) step₇))

        step₉ : (((a *ℤ c) *ℤ vi) +ℤ ((a *ℤ d) *ℤ s)) +ℤ (b *ℤ ((c *ℤ s) +ℤ (d *ℤ twelveTimesℤ s)))
                  ≡ (((a *ℤ c) *ℤ vi) +ℤ ((a *ℤ d) *ℤ s)) +ℤ (((b *ℤ c) *ℤ s) +ℤ ((twelveTimesℤ (b *ℤ d)) *ℤ s))
        step₉ = cong (λ t → (((a *ℤ c) *ℤ vi) +ℤ ((a *ℤ d) *ℤ s)) +ℤ t) step₈

        X = (a *ℤ c) *ℤ vi
        Y = (a *ℤ d) *ℤ s
        Z = ((b *ℤ c) *ℤ s) +ℤ ((twelveTimesℤ (b *ℤ d)) *ℤ s)

        step₁₀ : (X +ℤ Y) +ℤ Z ≡ X +ℤ (Y +ℤ Z)
        step₁₀ = +ℤ-assoc X Y Z

        twelveTerm = (twelveTimesℤ (b *ℤ d)) *ℤ s
        y2 = (b *ℤ c) *ℤ s

        fold₁ : Y +ℤ y2 ≡ ((a *ℤ d) +ℤ (b *ℤ c)) *ℤ s
        fold₁ = sym (*ℤ-distrib-left-+ℤ (a *ℤ d) (b *ℤ c) s)

        fold₂ : (((a *ℤ d) +ℤ (b *ℤ c)) *ℤ s) +ℤ twelveTerm ≡ b' *ℤ s
        fold₂ =
          trans
            (sym (*ℤ-distrib-left-+ℤ ((a *ℤ d) +ℤ (b *ℤ c)) (twelveTimesℤ (b *ℤ d)) s))
            refl

        innerFold : Y +ℤ (y2 +ℤ twelveTerm) ≡ b' *ℤ s
        innerFold =
          trans
            (sym (+ℤ-assoc Y y2 twelveTerm))
            (trans
              (cong (λ t → t +ℤ twelveTerm) fold₁)
              fold₂)
      in
      let
        pA : blk (linIJ a b w) i ≡ (X +ℤ Y) +ℤ (b *ℤ sum12ℤ w)
        pA = trans step₁ (trans step₂ step₃)

        pB : blk (linIJ a b w) i ≡ (X +ℤ Y) +ℤ (b *ℤ ((c *ℤ s) +ℤ (d *ℤ twelveTimesℤ s)))
        pB = trans pA step₄

        pC : blk (linIJ a b w) i ≡ (X +ℤ Y) +ℤ Z
        pC = trans pB (cong (λ t → (X +ℤ Y) +ℤ t) step₈)

        pD : blk (linIJ a b w) i ≡ X +ℤ (Y +ℤ Z)
        pD = trans pC (+ℤ-assoc X Y Z)

        pE : blk (linIJ a b w) i ≡ X +ℤ (b' *ℤ s)
        pE = trans pD (cong (λ t → X +ℤ t) innerFold)
      in
      trans pE (sym rhsForm)

    eq0 : (i : Fin4) → block₀ (linIJ a b w) i ≡ block₀ (linIJ (a *ℤ c) b' v) i
    eq0 = blkEq block₀ (λ x y u i → block₀-linIJ x y u i)

    eq1 : (i : Fin4) → block₁ (linIJ a b w) i ≡ block₁ (linIJ (a *ℤ c) b' v) i
    eq1 = blkEq block₁ (λ x y u i → block₁-linIJ x y u i)

    eq2 : (i : Fin4) → block₂ (linIJ a b w) i ≡ block₂ (linIJ (a *ℤ c) b' v) i
    eq2 = blkEq block₂ (λ x y u i → block₂-linIJ x y u i)
